server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##########
      classic_compatible: true
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 112.74.181.4
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
#    packages:
#      trust-all: true
    pool:
      enabled: false
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.NoteApp.entity
logging:
  level:
    com:
      example:
        mapper: debug
